project:
  type: website
  output-dir: _site
  render:
    - intro.qmd
    - 02_module_lecture.qmd
    - 03_module_lecture.qmd
    - 04_module_lecture.qmd

format:
  revealjs:
    width: 1920
    height: 1080
    theme: simple
    slide-number: true
    chalkboard: false
    preview-links: auto
    css: styles.css
    title-slide-attributes:
      data-background-image: images/background-placeholder.svg
      data-background-size: cover
execute:
  echo: false
